### ISSUE TITLE
您好,请问您的cloud页面是用什么做的呢?

### ISSUE THREAD

**Issue by threewater2** [Chaaoo/Chaaoo.github.io#1]
我看您的cloud页面很漂亮,您是自己写的,还是用的其它工具呢?
可以分享一下么?😀

**Comment by Chaaoo** [comment]
你说的是
cloud.chaoo.fun吗？
用的这个https://github.com/vcheckzen/FODI

**Comment by threewater2** [comment]
谢谢😊
